### ISSUE TITLE
Problem Encountered & Homework Finished

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/pokemon-mobile-exercise-renestadler#1]
Dear Mr. Stropek!
I've completed the current homework.
 While working on the project, I encountered the following error roughly every second time at deploying my app to the phone. I also noticed, that this error occured most likely after any execution error. Do you have an idea what the problem could be?

Kind Regards,
René Stadler

![image](https://user-images.githubusercontent.com/43231647/70453193-a39c9f80-1aa8-11ea-9e27-6c85fa25d106.png)

**Comment by rstropek** [comment]
Unfortunately, I do not have a solution for that problem. I spent some time with research, but did not find any promising results. I have never seen this problem on my PC, so I do not have a way to reproduce. Sorry that I cannot help.

Greetings,
Rainer Stropek
